.data

StringDatabaseStruct struct 
bird byte "bird.png",0
bird2 byte "bird2.png",0
spike byte "maps\small1.png",0
spike2 byte "maps\small2.png",0
def byte "maps\def.png",0
loser byte "loser.png",0
score byte "score.bmp",0

num0 byte "numbers\0.bmp",0
num1 byte "numbers\1.bmp",0
num2 byte "numbers\2.bmp",0
num3 byte "numbers\3.bmp",0
num4 byte "numbers\4.bmp",0
num5 byte "numbers\5.bmp",0
num6 byte "numbers\6.bmp",0
num7 byte "numbers\7.bmp",0
num8 byte "numbers\8.bmp",0
num9 byte "numbers\9.bmp",0


ding byte "ding.wav",0
fail byte "fail.wav",0

StringDatabaseStruct ends


ImgDatabaseStruct struct
def Img<>
loser Img<>
spike Img<>
spike2 Img<>
score Img<>
num0 Img<>
num1 Img<>
num2 Img<>
num3 Img<>
num4 Img<>
num5 Img<>
num6 Img<>
num7 Img<>
num8 Img<>
num9 Img<>
ImgDatabaseStruct ends